import * as fs from 'fs';

import type { ColorGroup, SemanticToken } from './types.js';

/**
 * Generates a Pure CSS Variables file with OKLCH colors.
 *
 * @param outputPath - Path where the CSS file will be written
 * @param colorGroups - Array of global color groups
 * @param lightTokens - Array of light mode semantic tokens
 * @param darkTokens - Array of dark mode semantic tokens
 */
export function generateCSSVariables(
  outputPath: string,
  colorGroups: ColorGroup[],
  lightTokens: SemanticToken[],
  darkTokens: SemanticToken[],
): void {
  const lines: string[] = [];

  // Header comment
  lines.push('/**');
  lines.push(' * Auto-generated by build.ts');
  lines.push(' * DO NOT EDIT MANUALLY');
  lines.push(' * ');
  lines.push(' * Source of truth: src/colors/README.md');
  lines.push(' * To update colors, modify README.md and run: npm run build');
  lines.push(' */');
  lines.push('');
  lines.push(':root {');

  // Generate global colors
  for (const group of colorGroups) {
    lines.push(`  /* Global Colors - ${group.groupName} */`);
    for (const color of group.colors) {
      const varName = formatCSSVarName(group.groupName, color.name);
      lines.push(`  --color-${varName}: ${color.oklch};`);
    }
    lines.push('');
  }

  // Generate semantic tokens - Light mode
  lines.push('  /* Semantic Tokens - Light Mode */');
  for (const token of lightTokens) {
    const varName = formatSemanticVarName(token.path);
    const value = token.resolvedOklch || token.resolvedHex || token.value;
    lines.push(`  --color-${varName}: ${value};`);
  }

  lines.push('}');
  lines.push('');

  // Dark mode
  lines.push('@media (prefers-color-scheme: dark) {');
  lines.push('  :root {');
  lines.push('    /* Semantic Tokens - Dark Mode */');

  for (const token of darkTokens) {
    const varName = formatSemanticVarName(token.path);
    const value = token.resolvedOklch || token.resolvedHex || token.value;
    lines.push(`    --color-${varName}: ${value};`);
  }

  lines.push('  }');
  lines.push('}');
  lines.push('');

  fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8');
}

/**
 * Formats a CSS variable name for global colors.
 *
 * @param groupName - The color group name (e.g., "Blue")
 * @param colorName - The full color name (e.g., "Blue50")
 * @returns Formatted CSS variable name (e.g., "blue-50")
 *
 * @example
 * ```typescript
 * formatCSSVarName("Blue", "Blue50") // returns "blue-50"
 * ```
 */
function formatCSSVarName(groupName: string, colorName: string): string {
  // Remove group prefix from color name
  // "Blue50" -> "50"
  const shade = colorName.replace(groupName, '');

  // Convert to kebab-case
  // "Blue" + "50" -> "blue-50"
  return `${groupName.toLowerCase()}-${shade.toLowerCase()}`;
}

/**
 * Formats a CSS variable name for semantic tokens.
 *
 * @param path - The token path as an array (e.g., ["Primary", "Main"])
 * @returns Formatted CSS variable name (e.g., "primary-main")
 *
 * @example
 * ```typescript
 * formatSemanticVarName(["Primary", "Main"]) // returns "primary-main"
 * ```
 */
function formatSemanticVarName(path: string[]): string {
  return path.map((p) => p.toLowerCase()).join('-');
}
